apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ylqpstsb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ylqpstsb:f4758e68f745d4f7cd3088ee241a4e6e36f7e620@sha256:4e4df0cc8f679a41ca87cca95a41de178ad39a2c441fd931d258dfa0ae73bfea
          name: container-image
